// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlB3d2kaZYyzBUxMg8neOphSnE5DouHLE',
    appId: '1:969525770235:web:09b036f3cfe38d86d0fd5e',
    messagingSenderId: '969525770235',
    projectId: 'fruitshup-d775d',
    authDomain: 'fruitshup-d775d.firebaseapp.com',
    storageBucket: 'fruitshup-d775d.firebasestorage.app',
    measurementId: 'G-DP05C6Z8HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyBLf-RW5PeD-Dy_91iVFByUD5zTrKek8',
    appId: '1:969525770235:android:daa44001ff4a1b40d0fd5e',
    messagingSenderId: '969525770235',
    projectId: 'fruitshup-d775d',
    storageBucket: 'fruitshup-d775d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1G3CaIRIjtGwQLgd5rjQ584pnJ5mLsc',
    appId: '1:969525770235:ios:f5f50edfb3b5bafed0fd5e',
    messagingSenderId: '969525770235',
    projectId: 'fruitshup-d775d',
    storageBucket: 'fruitshup-d775d.firebasestorage.app',
    androidClientId: '969525770235-r4vu3lhsuhier6tvlnaas44e8nctjl35.apps.googleusercontent.com',
    iosClientId: '969525770235-bo8haqi3rk55ivitko1blb8abc3bkh9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS1G3CaIRIjtGwQLgd5rjQ584pnJ5mLsc',
    appId: '1:969525770235:ios:f5f50edfb3b5bafed0fd5e',
    messagingSenderId: '969525770235',
    projectId: 'fruitshup-d775d',
    storageBucket: 'fruitshup-d775d.firebasestorage.app',
    androidClientId: '969525770235-r4vu3lhsuhier6tvlnaas44e8nctjl35.apps.googleusercontent.com',
    iosClientId: '969525770235-bo8haqi3rk55ivitko1blb8abc3bkh9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlB3d2kaZYyzBUxMg8neOphSnE5DouHLE',
    appId: '1:969525770235:web:9bc15bd4191de776d0fd5e',
    messagingSenderId: '969525770235',
    projectId: 'fruitshup-d775d',
    authDomain: 'fruitshup-d775d.firebaseapp.com',
    storageBucket: 'fruitshup-d775d.firebasestorage.app',
    measurementId: 'G-02Z49CWW5V',
  );
}
